基本的なCRUD処理の理解
DJMasaru/training pull request #1
Opened 2022-12-04 06:50 UTC by DJMasaru

Laravelで記述したコードでCRUD処理が出来るか作業したもの。
ルート処理で理解が追いついていない部分があり、具体的にはRoute::resourceを用いた場合。
上記によりリソースコントローラーの記述でCRUD処理を簡単に実装できるが、ルート先の記述に関して
シングルアクションコントローラにて理解を深めた方がいいのではないかと感じた。
また、CSSについてはある程度のマークアップを行いCRUD処理が出来るかどうかに重きを置いたため稚拙な表現が多くなってしまっている。

2022-12-04 07:15 UTC, mikana0918 commented on app/Http/Controllers/ArticleController.php
> +     */
php docいい感じやけどコピペ？
自分で常に描けるようにしておくといいね

2022-12-04 07:19 UTC, mikana0918 commented on app/Http/Controllers/ArticleController.php
> +     */
phpstormとか使うと、ホバーしてadd phpdocみたいな項目から一発でphpdoc自動生成できるから、vscodeやめてphpstormにうつったほうがいいかも

https://www.jetbrains.com/phpstorm/

2022-12-04 07:21 UTC, mikana0918 commented on app/Http/Controllers/ArticleController.php
> +     * @return \Illuminate\Http\Response
```suggestion
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
```

2022-12-04 07:26 UTC, mikana0918 commented on app/Http/Controllers/ArticleController.php
> +
```suggestion
```

使ってない箇所は消そう

2022-12-04 07:28 UTC, mikana0918 commented on app/Http/Controllers/ArticleController.php
> +     * @return \Illuminate\Http\Response
```suggestion
     * @return \Illuminate\Http\Response
```
ここも上のコメントと同じで、型が違うね。上と一緒のになおしといて

2022-12-04 07:28 UTC, mikana0918 commented on app/Http/Controllers/ArticleController.php
> +        //
```suggestion
```

2022-12-04 07:29 UTC, mikana0918 commented on app/Http/Controllers/ArticleController.php
> +     * @return \Illuminate\Http\Response
```suggestion
     * @return \Illuminate\Http\RedirectResponse
```
こっちが正で、useをするとこう書き換えになる

 ```php
 use Illuminate\Http\RedirectResponse
 // (略)
 @return RedirectResponse
 ```

2022-12-04 07:30 UTC, mikana0918 commented on app/Http/Controllers/ArticleController.php
> +     * @return \Illuminate\Http\Response
```suggestion
     * @return \Illuminate\Http\Response
```
これもviewの型（上で指摘したやつ）に直しとこう

2022-12-04 07:31 UTC, mikana0918 commented on app/Http/Controllers/ArticleController.php
> +    public function show(Article $article)
Articleモデルを受け取るよりも、showの場合はidを受け取る方が無難だと思う。
RESTful APIの場合は、idを受け取って、モデルで`Article::find($id)`がいい。

2022-12-04 07:32 UTC, mikana0918 commented on app/Http/Controllers/ArticleController.php
> +    public function show(Article $article)
```suggestion
    public function show(int $id)
```

2022-12-04 07:32 UTC, mikana0918 commented on app/Http/Controllers/ArticleController.php
> +        return view('layouts/show', compact('article'));
```
$article = Article::find($id);

return view('layouts/show', compact('article'));
```

2022-12-04 07:33 UTC, mikana0918 commented on app/Http/Controllers/ArticleController.php
> +     * @return \Illuminate\Http\Response
```suggestion
     * @return \Illuminate\Http\Response
```
phpdoc治しといて

2022-12-04 07:34 UTC, mikana0918 commented on app/Http/Controllers/ArticleController.php
> +    public function edit(Article $article)
```suggestion
    public function edit(Article $article)
```
モデル型をコントローラのメソッドの引数にしない方がいい。

基本的には、汎用のResponseもしくはカスタムバリデーションResponseを当てるべき。

2022-12-04 07:40 UTC, mikana0918 requested changes
色々コメントしたので修正よろしく

2022-12-04 07:40 UTC, mikana0918 commented on app/Http/Controllers/ArticleController.php
> +    public function edit(Article $article)
理由としては、不正なモデルが来ても、DBに保存、アップデートするとデータが狂ってアプリケーションがバグりまくるから。バリデーションを基本的にかますべき。もらったデータを直接DBに入れるのは絶対に禁止

2022-12-04 07:40 UTC, mikana0918 commented on app/Http/Controllers/ArticleController.php
> +     * @return \Illuminate\Http\Response
```suggestion
     * @return \Illuminate\Http\Response
```
RedirectResponseに変えといて

2022-12-04 07:40 UTC, mikana0918 commented on app/Http/Controllers/ArticleController.php
> +     * @return \Illuminate\Http\Response
RedirectResponse

2022-12-04 07:40 UTC, mikana0918 commented on app/Http/Controllers/ArticleController.php
> +        $article->fill($form)->save();
ここ、フォームに入力されたの直接DBにぶち込んでるけど、セキュリティ的にも危ない（ SQLインジェクションなど）ので、基本的にformリクエストはバリデーションクラスを別途作成すべきかな（今はやらなくていいけど）

2022-12-04 07:40 UTC, mikana0918 commented on app/Http/Controllers/ArticleController.php
> +        return redirect(route('article.show', ['article' => $article->id]));
```suggestion
        return redirect(route('article.show', ['article' => $article->id]));
```
compact()使うところとarrayでそのまま返しているところ、二つあるからどちらかで統一した方がいいかも

2022-12-04 07:40 UTC, mikana0918 commented on resources/views/layouts/show.blade.php
> +            <form action="{{route('article.destroy', ['article' => $article->id])}}" method="post" onsubmit="return confirm('本当に削除しますか？')">
ここ、destoryにid渡してるだけやのにcontrollerでarticleモデルもらってることになってて謎やな 🤔  もらったidそのままdestroyしたらいいよ

2022-12-04 07:40 UTC, mikana0918 commented on routes/web.php
> +Route::resource('article', ArticleController::class);
resourceルーティングあんまり使わないけど、今回はCRUDリソースやりたいだけやったからこれでいいよ。綺麗なCRUD以外の時に融通効かないから実戦ではあんまり見ないけど

2022-12-04 07:40 UTC, mikana0918 commented on routes/web.php
> +
```suggestion
```
いらないところ消していいと思う

2022-12-04 07:57 UTC, mikana0918 commented on app/Models/Article.php
> +        'title', 'content',
これは必要やからOK 🙆‍♂️

2022-12-04 07:57 UTC, mikana0918 commented on app/Http/Controllers/HogehogeController.php
> +<?php
このファイル、使ってないから不要なら消そうか

2022-12-04 08:00 UTC, mikana0918 commented on database/migrations/2022_12_03_185249_create_hogehoges_table.php
> +        });
hogehogesテーブル多分使ってないよな？
使ってない場合、このマイグレーションファイルもろとも消しちゃった方がいいかも。

理由としてはmixhostに行った時にも、php artisan migrateをするとこのデバッグ用みたいなテーブル作成されちゃうので

2022-12-04 08:02 UTC, mikana0918 commented
@DJMasaru あと下記もやるようにしよう。

- Articleモデル(articlesテーブル）のFactoryの作成
- Articleモデル(articlesテーブル）のFactoryを使ったSeederの作成

twitter-makrup-backendでもやってたと思うから、確認がてらやってみて。

これが必要な理由としては、mixhostにデプロイしてから手作業で初期データ入れるの面倒だから、
seederを入れてささっとデータを用意しちゃいたい。

paginationを10件ごとにするから、seederで50個くらいデータ作って欲しい

2022-12-04 08:06 UTC, mikana0918 commented
> 上記によりリソースコントローラーの記述でCRUD処理を簡単に実装できるが、ルート先の記述に関して
> シングルアクションコントローラにて理解を深めた方がいいのではないかと感じた。

うん、これはあるかも。余力があれば書き直してもいいと思う。
php artisan route:listにあるやつをそのままroute.phpに書き写せばいいと思う。

2022-12-04 08:07 UTC, mikana0918 requested changes
↑一旦、コメントにある項目できるところまで対応してみて

2022-12-04 14:53 UTC, DJMasaru commented on app/Http/Controllers/ArticleController.php
> +     */
確かこのphp docは、ArticleControllerを下記のようなコマンドで作成したときから書かれていたように思う。
php artisan make:model Article -mcr
phpstormは今後を見据えて前向きに導入の検討をする！

2022-12-04 16:34 UTC, DJMasaru commented
> @DJMasaru あと下記もやるようにしよう。
> 
> * Articleモデル(articlesテーブル）のFactoryの作成
> * Articleモデル(articlesテーブル）のFactoryを使ったSeederの作成
> 
作成完了！！！日本語で入れるように設定したら、文法がおかしなひらがなの羅列がされたデータが入ってしまった、、、

2022-12-05 14:24 UTC, DJMasaru commented on app/Http/Controllers/ArticleController.php
> +
当該箇所修正済。

2022-12-05 14:27 UTC, DJMasaru commented on app/Http/Controllers/ArticleController.php
> +     * @return \Illuminate\Http\Response
<img width="784" alt="スクリーンショット 2022-12-05 23 26 56" src="https://user-images.githubusercontent.com/91363928/205661352-c45e4650-dd9d-4825-8c81-b2f940edd31f.png">
上記の指摘通りに修正したが、そのままでよいか。

2022-12-05 14:29 UTC, DJMasaru commented on app/Http/Controllers/ArticleController.php
> +        //
ここはどのように修正すればよいか。

2022-12-05 14:33 UTC, DJMasaru commented on app/Http/Controllers/ArticleController.php
> +     * @return \Illuminate\Http\Response
<img width="1380" alt="スクリーンショット 2022-12-05 23 32 40" src="https://user-images.githubusercontent.com/91363928/205662764-3ef2b7c9-be34-41a7-a0b6-bb9f064bb2c5.png">
画像のように修正した。これでよいか。

2022-12-05 14:34 UTC, DJMasaru commented on app/Http/Controllers/ArticleController.php
> +     * @return \Illuminate\Http\Response
<img width="784" alt="スクリーンショット 2022-12-05 23 26 56" src="https://user-images.githubusercontent.com/91363928/205662973-51a6d6aa-e94f-4722-aeca-2829eec71db3.png">
この画像の内容で合っているだろうか。

2022-12-05 14:44 UTC, DJMasaru commented on app/Http/Controllers/HogehogeController.php
> +<?php
削除済。

2022-12-05 14:45 UTC, DJMasaru commented on database/migrations/2022_12_03_185249_create_hogehoges_table.php
> +        });
削除済。

2022-12-05 14:46 UTC, DJMasaru commented on routes/web.php
> +
削除済。

2022-12-05 14:49 UTC, DJMasaru commented on app/Http/Controllers/ArticleController.php
> +     * @return \Illuminate\Http\Response
修正済。

2022-12-05 14:49 UTC, DJMasaru commented on app/Http/Controllers/ArticleController.php
> +     * @return \Illuminate\Http\Response
修正済。

2022-12-05 14:50 UTC, DJMasaru commented on app/Http/Controllers/ArticleController.php
> +     * @return \Illuminate\Http\Response
@return \Illuminate\Http\RedirectResponseに修正済。

2022-12-05 14:51 UTC, DJMasaru commented on app/Http/Controllers/ArticleController.php
> +     * @return \Illuminate\Http\Response
@return \Illuminate\Http\Response\RedirectResponseに修正済。

2022-12-05 14:52 UTC, DJMasaru commented on app/Http/Controllers/ArticleController.php
> +     * @return \Illuminate\Http\Response
@return \Illuminate\Http\RedirectResponseに修正済。

2022-12-05 14:53 UTC, DJMasaru commented on app/Http/Controllers/ArticleController.php
> +     * @return \Illuminate\Http\Response
@return \Illuminate\Http\RedirectResponseに修正済。

2022-12-05 18:12 UTC, mikana0918 commented on app/Http/Controllers/ArticleController.php
> +        return view('layouts/show', compact('article'));
@DJMasaru 
```php
$article = Article::find($article->id);

return view('layouts/show', compact('article'));
```

2022-12-05 18:12 UTC, mikana0918 commented on app/Http/Controllers/ArticleController.php
> +        //
@DJMasaru 34行目`//`を消す

2022-12-05 18:13 UTC, mikana0918 commented on app/Http/Controllers/HogehogeController.php
> +<?php
@DJMasaru pushした？消せてないと思う

2022-12-05 18:13 UTC, mikana0918 commented on app/Models/Hogehoge.php
> +<?php
@DJMasaru このモデルも不要なら消そう

2022-12-05 18:13 UTC, mikana0918 commented on database/migrations/2022_12_03_185249_create_hogehoges_table.php
> +        });
@DJMasaru pushした？これも消せてない

2022-12-06 14:39 UTC, DJMasaru commented on app/Http/Controllers/ArticleController.php
> +        //
削除済。

2022-12-06 14:41 UTC, DJMasaru commented on app/Http/Controllers/ArticleController.php
> +        return view('layouts/show', compact('article'));
修正済。エラー出ず。

2022-12-06 16:19 UTC, merged